import React from 'react'

export default function TermsCondition() {
  return (
    <>
     <div className="policy">
                <div className="container">
                    <h2 className="policy-main-head">TERMS AND CONDITIONS</h2>

                    <p className="policy-para">
                        Be sure to read the privacy policy that applies to all bookings made with Zerzura LLC. Zerzura LLC (“us”, “we”, or “our”) operates explorertours.ae (hereinafter referred to as “Service”). Our Privacy Policy governs your visit to explorertours.ae, and explains how we collect, safeguard, and disclose information that results from your use of our Service. We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions. Our Terms and Conditions (“Terms”) govern all use of our Service and together with the Privacy Policy constitutes your agreement with us (“Agreement”).
                    </p>

                    <h3 className="policy-sub-heading">DEFINITIONS</h3>

                    <ul className="dot-style">
                        <li>
                            <p className="policy-para">
                                <span>SERVICE :</span> means the https://explorertours.ae/ website operated by Zerzura LLC.
                            </p>
                        </li>
                        <li>
                            <p className="policy-para">
                                <span>PERSONAL DATA :</span> means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).
                            </p>
                        </li>
                        <li>
                            <p className="policy-para">
                                <span>USAGE DATA :</span> is data collected automatically either generated by the use of Service or from the Service infrastructure itself (for example, the duration of a page visit).
                            </p>
                        </li>
                        <li>
                            <p className="policy-para">
                                <span>COOKIES :</span> are small files stored on your device (computer or mobile device).
                            </p>
                        </li>
                        <li>
                            <p className="policy-para">
                                <span>DATA CONTROLLER :</span> means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.
                            </p>
                        </li>
                        <li>
                            <p className="policy-para">
                                <span>DATA PROCESSORS (OR SERVICE PROVIDERS) :</span> means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.
                            </p>
                        </li>
                        <li>
                            <p className="policy-para">
                                <span>DATA SUBJECT :</span> is any living individual who is the subject of Personal Data.
                            </p>
                        </li>
                        <li>
                            <p className="policy-para">
                                <span>THE USER :</span> is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.
                            </p>
                        </li>
                    </ul>

                    <h3 className="policy-sub-heading">INFORMATION COLLECTION & USE</h3>

                    <p className="policy-para">
                        We collect several different types of information for various purposes to provide and improve our Service to you.
                    </p>

                    <h4 className="policy-sub-heading">TYPE OF DATA COLLECTED</h4>

                    <h5 className="policy-sub-sub-heading">Personal Data</h5>

                    <p className="policy-para">
                        While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (“Personal Data”). Personally, identifiable information may include, but is not limited to:
                    </p>

                    <ul className="dot-style">
                        <li>
                            <p className="policy-para">- Email address</p>
                        </li>
                        <li>
                            <p className="policy-para">- First name and last name</p>
                        </li>
                        <li>
                            <p className="policy-para">-Phone number</p>
                        </li>
                        <li>
                            <p className="policy-para">- Address, Country, State, Province, ZIP/Postal code, City</p>
                        </li>
                        <li>
                            <p className="policy-para">- Cookies and Usage Data</p>
                        </li>
                    </ul>

                    <p className="policy-para">
                        We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link.
                    </p>

                    <h5 className="policy-sub-sub-heading">Usage Data</h5>

                    <p className="policy-para">
                        We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through any device (“Usage Data”). This Usage Data may include information such as your computer’s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data. When you access Service with a device, this Usage Data may include information such as the type of device you use, your device unique ID, the IP address of your device, your device operating system, the type of Internet browser you use, unique device identifiers and other diagnostic data.
                    </p>

                    <h5 className="policy-sub-sub-heading">Location Data</h5>

                    <p className="policy-para">
                        We may use and store information about your location if you give us permission to do so (“Location Data”). We use this data to provide features of our Service, to improve and customize our Service. You can enable or disable location services when you use our Service at any time by way of your device settings.
                    </p>

                    <h5 className="policy-sub-sub-heading">Tracking Cookies Data</h5>

                    <p className="policy-para">
                        We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information. Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyze our Service. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service. Examples of Cookies we use: Session Cookies, Preference Cookies, Security Cookies & Advertising Cookies.
                    </p>

                    <h5 className="policy-sub-sub-heading">Other Data</h5>

                    <p className="policy-para">
                        While using our Service, we may also collect the following information: sex, age, date of birth, place of birth, passport details, citizenship, registration at place of residence and actual address, telephone number (work, mobile), details of documents on education, qualification, professional training, employment agreements, NDA agreements, information on bonuses and compensation, information on marital status, family members, social security (or other taxpayer identification) number, office location and other data.
                    </p>

                    <h3 className="policy-sub-heading">USE OF DATA</h3>

                    <p className="policy-para">
                        Zerzura LLC uses the collected data for various purposes:
                    </p>

                    <ul className="dot-style">
                        <li><p className="policy-para">0.1. to provide and maintain our Service;</p></li>
                        <li><p className="policy-para">0.2. to notify you about changes to our Service;</p></li>
                        <li><p className="policy-para">0.3. to allow you to participate in interactive features of our Service when you choose to do so;</p></li>
                        <li><p className="policy-para">0.4. to provide customer support;</p></li>
                        <li><p className="policy-para">0.5. to gather analysis or valuable information so that we can improve our Service;</p></li>
                        <li><p className="policy-para">0.6. to monitor the usage of our Service;</p></li>
                        <li><p className="policy-para">0.7. to detect, prevent and address technical issues;</p></li>
                        <li><p className="policy-para">0.8. to fulfill any other purpose for which you provide it;</p></li>
                        <li><p className="policy-para">0.9. to carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection;</p></li>
                        <li><p className="policy-para">0.10. to provide you with notices about your account and/or subscription, including expiration and renewal notices, email-instructions, etc.;</p></li>
                        <li><p className="policy-para">0.11. to provide you with news, special offers</p></li>
                    </ul>

                </div>
            </div>
    </>
  )
}
